// Code generated by MockGen. DO NOT EDIT.
// Source: ./filesystem/fs.go

// Package mock_filesystem is a generated GoMock package.
package mock_filesystem

import (
        filesystem "fsync/filesystem"
        fs "io/fs"
        reflect "reflect"

        gomock "github.com/golang/mock/gomock"
)

// MockFileManagerInterface is a mock of FileManagerInterface interface.
type MockFileManagerInterface struct {
        ctrl     *gomock.Controller
        recorder *MockFileManagerInterfaceMockRecorder
}

// MockFileManagerInterfaceMockRecorder is the mock recorder for MockFileManagerInterface.
type MockFileManagerInterfaceMockRecorder struct {
        mock *MockFileManagerInterface
}

// NewMockFileManagerInterface creates a new mock instance.
func NewMockFileManagerInterface(ctrl *gomock.Controller) *MockFileManagerInterface {
        mock := &MockFileManagerInterface{ctrl: ctrl}
        mock.recorder = &MockFileManagerInterfaceMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileManagerInterface) EXPECT() *MockFileManagerInterfaceMockRecorder {
        return m.recorder
}

// Mkdir mocks base method.
func (m *MockFileManagerInterface) Mkdir(name string) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Mkdir", name)
        ret0, _ := ret[0].(error)
        return ret0
}

// Mkdir indicates an expected call of Mkdir.
func (mr *MockFileManagerInterfaceMockRecorder) Mkdir(name string) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mkdir", reflect.TypeOf((*MockFileManagerInterface)(nil).Mkdir), name)
}

// ReadDir mocks base method.
func (m *MockFileManagerInterface) ReadDir(name string) ([]fs.DirEntry, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "ReadDir", name)
        ret0, _ := ret[0].([]fs.DirEntry)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockFileManagerInterfaceMockRecorder) ReadDir(name interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockFileManagerInterface)(nil).ReadDir), name)
}

// ReadDirectory mocks base method.
func (m *MockFileManagerInterface) ReadDirectory(dirPath string) (*filesystem.Directory, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "ReadDirectory", dirPath)
        ret0, _ := ret[0].(*filesystem.Directory)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// ReadDirectory indicates an expected call of ReadDirectory.
func (mr *MockFileManagerInterfaceMockRecorder) ReadDirectory(dirPath interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDirectory", reflect.TypeOf((*MockFileManagerInterface)(nil).ReadDirectory), dirPath)
}

// ReadFile mocks base method.
func (m *MockFileManagerInterface) ReadFile(name string) ([]byte, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "ReadFile", name)
        ret0, _ := ret[0].([]byte)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockFileManagerInterfaceMockRecorder) ReadFile(name interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockFileManagerInterface)(nil).ReadFile), name)
}

// Remove mocks base method.
func (m *MockFileManagerInterface) Remove(name string) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Remove", name)
        ret0, _ := ret[0].(error)
        return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockFileManagerInterfaceMockRecorder) Remove(name interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockFileManagerInterface)(nil).Remove), name)
}

// WriteFile mocks base method.
func (m *MockFileManagerInterface) WriteFile(name string, data []byte) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "WriteFile", name, data)
        ret0, _ := ret[0].(error)
        return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockFileManagerInterfaceMockRecorder) WriteFile(name, data interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockFileManagerInterface)(nil).WriteFile), name, data)
}